version "4.12"

class DevredsHUD : BaseStatusBar
{
	
	HUDFont MegaFont;
	HUDFont BigFont;
	HUDFont TinyFont;
	
	int health_catchup;
	
	int dm_lerp_tics;
	bool damagebar_lit;
	
	int previous_ammo;
	int clipcasing_delay;
	bool casing_spent;
	
	String casing_slots[9];
	int current_casing_slot;
	double casing_x_spacing;
	
	int ammotray_lerp;
	
	int clip_tray_dist;
	int clip_tray_lerp;
	int clip_tray_up;
	
	int ammotray_ammospent;
	bool ammotray_bigshot;
	
	int ammoclip_lerp_delay;
	
	int shell_tray_dist;
	
	int rocket_tray_dist;
	
	int cell_tray_dist;
	
	string current_ammotype;
	string previous_ammotype;
	bool ammotype_switched;
	
	bool crit_mug_fade_in;
	float crit_mug_alpha;
	
	int player_command;
	Array<String> custom_ammotype;
	
	double deltaTic;
	
	override void Init()
	{
		Super.Init();
		
		health_catchup = 0;
		dm_lerp_tics = 0;
		damagebar_lit = false;
		
		previous_ammo = 0;
		clipcasing_delay = 1;
		casing_spent = false;
		casing_x_spacing = -52;

		casing_slots[0] = "NOFRAM_0";
		casing_slots[1] = "NOFRAM_0";
		casing_slots[2] = "NOFRAM_0";
		casing_slots[3] = "NOFRAM_0";
		casing_slots[4] = "NOFRAM_0";
		casing_slots[5] = "NOFRAM_0";
		casing_slots[6] = "NOFRAM_0";
		casing_slots[7] = "NOFRAM_0";
		casing_slots[8] = "NOFRAM_0";
		current_casing_slot = 0;
		
		ammotray_lerp = 0;
		ammotray_ammospent = 0;
		ammotray_bigshot = false;
		clip_tray_dist = 10;
		shell_tray_dist = 12;
		rocket_tray_dist = 16;
		cell_tray_dist = 8;
		clip_tray_lerp = 10;
		clip_tray_up = 0;
		
		ammoclip_lerp_delay = 1;
		ammotype_switched = false;
		
		crit_mug_fade_in = false;
		crit_mug_alpha = 0.0;
		
		MegaFont = HUDFont.Create("HUDFONT_DOOM");
		BigFont = HUDFont.Create("SMALLFONT");
		TinyFont = HUDFont.Create("INDEXFONT");
		
		//Get custom sprite names from DHUDCUST lump.
		int custom_ammo_index = Wads.FindLump("DHUDAMMO.txt", 0);
		String custom_ammo_data = Wads.ReadLump(custom_ammo_index);
		
		custom_ammo_data.Split(custom_ammotype, "\n");
		
	}
	
	override void Draw (int state, double TicFrac)
	{
		Super.Draw (state, TicFrac);

		if (state == HUD_StatusBar)
		{
			BeginStatusBar();
			D_StatusHUD (TicFrac);
		}
		else if (state == HUD_Fullscreen)
		{
			BeginHUD();
			D_FullHUD (TicFrac);
		}
	}
	
	void D_StatusHUD (double TicFrac)
	{
		return;
	}
	
	void D_FullHUD (double TicFrac)
	{
		//This variable is a test to help maintain a consistent framerate for the animations.
		deltaTic = TicFrac;
		
		
		
		//Health bar is designated here.
		DrawImage ("HPARBAR",(55,0),DI_SCREEN_LEFT_BOTTOM);
		
		//-----------------------------|Health Bar|------------------------
		//Damaged bar interpolation.
		if (CPlayer.health > health_catchup)
		{
			health_catchup = CPlayer.health;
		}
		else if (CPlayer.health < health_catchup && dm_lerp_tics <= 0)
		{
			health_catchup -= 1;
			damagebar_lit ^= true;
			dm_lerp_tics = 2;
		}
		dm_lerp_tics -= TicFrac;
		
		if (damagebar_lit)
		{
			DrawBar ("HPBARDM1", "HPBARNO", health_catchup, 100, (62, -7), SHADER_HORZ, DI_SCREEN_LEFT_BOTTOM);
		}
		else
		{
			DrawBar ("HPBARDM2", "HPBARNO", health_catchup, 100, (62, -7), SHADER_HORZ, DI_SCREEN_LEFT_BOTTOM);
		}
		
		
		if (CPlayer.health > 25){
			DrawString (MegaFont, FormatNumber(CPlayer.health, 3), (0,-35), DI_SCREEN_LEFT_BOTTOM|DI_TEXT_ALIGN_LEFT, Font.CR_GREEN);
			DrawBar ("HPBAR1", "HPBARNO", CPlayer.health, 100, (62, -7), SHADER_HORZ, DI_SCREEN_LEFT_BOTTOM);
		}
		else{
			DrawString (MegaFont, FormatNumber(CPlayer.health, 3), (0,-35), DI_SCREEN_LEFT_BOTTOM|DI_TEXT_ALIGN_LEFT, Font.CR_BRICK);
			DrawBar ("HPBAR0", "HPBARNO", CPlayer.health, 100, (62, -7), SHADER_HORZ, DI_SCREEN_LEFT_BOTTOM);
		}
		
		if (CPlayer.health > 100)
		{
			DrawString (MegaFont, FormatNumber(CPlayer.health, 3), (0,-35), DI_SCREEN_LEFT_BOTTOM|DI_TEXT_ALIGN_LEFT, Font.CR_SAPPHIRE);
		}
		DrawBar ("HPBAR2", "HPBARNO", CPlayer.health - 100, 100, (62, -7), SHADER_HORZ, DI_SCREEN_LEFT_BOTTOM);
		
		//---------------------|Armor Display|---------------------------
		
		if (GetArmorAmount() > 100)
		{
			DrawString (BigFont, FormatNumber(GetArmorAmount(), 3), (1,-9), DI_SCREEN_LEFT_BOTTOM|DI_TEXT_ALIGN_LEFT, Font.CR_CYAN);
		}
		else
		{
			DrawString (BigFont, FormatNumber(GetArmorAmount(), 3), (1,-9), DI_SCREEN_LEFT_BOTTOM|DI_TEXT_ALIGN_LEFT, Font.CR_BLUE);
		}
		
		DrawBar ("APBAR1", "APBAR0", GetArmorAmount(), 100, (62, -1), SHADER_HORZ, DI_SCREEN_LEFT_BOTTOM);
		DrawBar ("APBAR2", "APBAR0", GetArmorAmount() - 100, 100, (62, -1), SHADER_HORZ, DI_SCREEN_LEFT_BOTTOM);
		
		//--------------------|Ammo Counter|------------------------
		//Here we draw the ammo tray, display ammo and animate ammo spent.
		Inventory ammotype1, ammotype2;
		[ammotype1, ammotype2] = GetCurrentAmmo();
		
		bool check_ammotype;
		
		if (ammotype1 != null) {
			current_ammotype = ammotype1.GetClassName();
		} else {
			current_ammotype = "None";
		}
		
		if (current_ammotype == "Clip" || current_ammotype == "Shell" || current_ammotype == "RocketAmmo" || current_ammotype == "Cell") {
			check_ammotype = true;
		}
		else {
			check_ammotype = false;
		}
		
		//This section is to show ammo in the tray.
		if (ammotype1 != null)
		{
			String ammo_sprite;
			int ammo_spacing;
			int ammo_spacingFix;
			int ammo_traySpace;
			int ammo_trayFix;
			int ammo_displayAmount;
			
			if (current_ammotype == "Clip")
			{
				ammo_traySpace = 9;
				ammo_trayFix = 1;
				ammo_spacing = clip_tray_dist;
				ammo_spacingFix = 0;
				ammo_sprite = "TR_CLIP0";
			}
			else if (current_ammotype == "Shell")
			{
				ammo_traySpace = 8;
				ammo_trayFix = 0;
				ammo_spacing = shell_tray_dist;
				ammo_spacingFix = -2;
				ammo_sprite = "TR_SHEL0";
			}
			else if (current_ammotype == "RocketAmmo")
			{
				ammo_traySpace = 6;
				ammo_trayFix = 0;
				ammo_spacing = rocket_tray_dist;
				ammo_spacingFix = 0;
				ammo_sprite = "TR_ROCK0";
			}
			if (current_ammotype == "Cell")
			{
				ammo_traySpace = 12;
				ammo_trayFix = 1;
				ammo_spacing = cell_tray_dist;
				ammo_spacingFix = 3;
				ammo_sprite = "TR_CELL0";
			}
			else if (!check_ammotype)
			{
				//Set generic values first.
				ammo_traySpace = 9;
				ammo_trayFix = 1;
				ammo_spacing = clip_tray_dist;
				ammo_spacingFix = 0;
				ammo_sprite = "TR_GNRC0";
				//Get custom sprites from string array here.
				foreach(at : custom_ammotype) {
					//Then set custom values.
					Array<String> at_values; at.Split(at_values, ", ");
					String ammo_name;
					ammo_name = at_values[1].Mid(9);
					if (ammo_name == current_ammotype) {
						String at_traySpace = at_values[4].Mid(11);
						ammo_traySpace = at_traySpace.ToInt();
						ammo_trayFix = 1;
						String at_ammo_spacing = at_values[3].Mid(10);
						ammo_spacing = at_ammo_spacing.ToInt();
						ammo_spacingFix = 0;
						ammo_sprite = at_values[2].Mid(12);
						break;
					}
				}
			}
			
			if (ammotype1.Amount >= ammo_traySpace) {
				ammo_displayAmount = ammo_traySpace;
			} else {
				ammo_displayAmount = ammotype1.Amount;
			}
			
			for (int f = 1; f < ammo_displayAmount + 1; f++) {
					DrawImage(ammo_sprite, (ammo_spacing * (f - ammo_traySpace - ammo_trayFix - 1) + clip_tray_lerp + ammo_spacingFix, -2 - clip_tray_up), DI_SCREEN_RIGHT_BOTTOM);
				}
		}
		
		if (ammotype1 != null && ammotype1.Amount != previous_ammo)
		{	
			if (current_ammotype != previous_ammotype) {
				clip_tray_up = -30;
				previous_ammotype = current_ammotype;
				ammotray_lerp = 30;
			}
			else if (ammotype1.Amount > previous_ammo) {
				clip_tray_up = 8;
			}
			else{
				//This line below starts the casing animation. Change it to use the arrays.
				bool tray_sled = false;
				ammotray_ammospent = previous_ammo - ammotype1.Amount;
				while (ammotray_ammospent > 0) {
					if (!tray_sled) {
						clip_tray_lerp = 10 * ammotray_ammospent;
						tray_sled = true;
					}
					if (ammotray_ammospent >= 10) {
						ammotray_bigshot = true;
						ammotray_ammospent = 1;
					}
					casing_slots[current_casing_slot] = "TRGNRU_0";
					current_casing_slot += 1;
					if (current_casing_slot > 8) {
						current_casing_slot = 0;
					}
					if (clip_tray_lerp > 100) {
						clip_tray_lerp = 100;
					}
					ammotray_ammospent -= 1;
				}
			}
			previous_ammo = ammotype1.Amount;
		}
		//Setting static arrays here.
		static const String CASING_SHEL[] =
		{
			"TRSHLU_", "TRSHLB_", "TRSHLC_"
		};
		
		static const String CASING_CLIP[] =
		{
			"TRCLPU_", "TRCLBU_", "TRCLCU_"
		};
		
		
		//Tic timers go here
		if (clipcasing_delay <= 0) {
			for (int fr = 0; fr < 9; fr++) {
				int change_next_frame;
				
				String this_casing_slot = casing_slots[fr].Mid(7);
				
				change_next_frame = this_casing_slot.ToInt() + 1;
				casing_slots[fr].Substitute(this_casing_slot, String.Format("%d", change_next_frame));
				
			}
			clipcasing_delay = devrhud_spentcasing_tics;
		}
		clipcasing_delay -= TicFrac;
		
		
		if (ammoclip_lerp_delay <= 0) {
			//Tray lerping
			if (ammotray_lerp > 0) {
				ammotray_lerp -= 8;
			}
			else if (ammotray_lerp < 0) {
				ammotray_lerp += 1;
			}
			//Clip Lerping
			if (clip_tray_lerp > 0) {
				clip_tray_lerp -= 2;
			}
			if (clip_tray_up > 0) {
				clip_tray_up -= 2;
			}
			else if (clip_tray_up < 0) {
				clip_tray_up += 8;
			}
			ammoclip_lerp_delay = devrhud_traylerp_tics;
		}
		ammoclip_lerp_delay -= TicFrac;
		
		
		//This section controls the spent casing animations. (Updated)
		for (int fr = 0; fr < 9; fr++) {
			String frame_name = casing_slots[fr].Mid(0, 6);
			bool get_generic = false;
			
			if (frame_name == "TRGNRU") {
				get_generic = true;
				if (current_ammotype == "Clip"){
					casing_slots[fr].Replace("TRGNRU", CASING_CLIP[random(0,2)]);
					casing_x_spacing = -52;
				}
				else if (current_ammotype == "Shell") {
					casing_slots[fr].Replace("TRGNRU", CASING_SHEL[random(0,2)]);
					casing_x_spacing = -52;
				}
				else if (current_ammotype == "RocketAmmo") {
					casing_slots[fr].Replace("TRGNRU", "TRROCU");
					casing_x_spacing = -52;
				}
				else if (current_ammotype == "Cell") {
					if (ammotray_bigshot) {
						casing_slots[fr].Replace("TRGNRU", "TRCELA");
					} else {
						casing_slots[fr].Replace("TRGNRU", "TRCELU");
					}
					casing_x_spacing = -58;
				}
				else if (!check_ammotype) {
					foreach(at : custom_ammotype) {
					//int ammo_name_left = at.RightIndexOf("-ammotype=") + 1;
						Array<String> at_values; at.Split(at_values, ", ");
						String ammo_name;

						ammo_name = at_values[1].Mid(9);
						
						if (ammo_name == current_ammotype) {
							if (ammotray_bigshot) {
								casing_slots[fr].Replace("TRGNRU", at_values[8].Mid(17, 6));
							} else {
								String at_spent_fr[] = { at_values[5].Mid(11, 6), at_values[6].Mid(11, 6), at_values[7].Mid(11, 6) };
								casing_slots[fr].Replace("TRGNRU", at_spent_fr[random(0,2)]);
							}
							String at_spent_pos = at_values[9].Mid(12);
							casing_x_spacing = -52 - at_spent_pos.ToInt();
							break;
						}
						
					}
					
					
				}
				ammotray_bigshot = false;
			}
			
			String this_frame = casing_slots[fr].Mid(7);
			
			if (this_frame.ToInt() != 0 && this_frame.ToInt() <= 8) {
				DrawImage(casing_slots[fr], (casing_x_spacing,0), DI_SCREEN_RIGHT_BOTTOM);
			}
			
		}
		
		//Here we draw the counter overlay.
		DrawImage ("AMMOCNTR",(-13,0),DI_SCREEN_RIGHT_BOTTOM);
		
		if (ammotype1 != null)
		{
			DrawString (MegaFont, FormatNumber(ammotype1.Amount, 3), (-3,-43), DI_SCREEN_RIGHT_BOTTOM|DI_TEXT_ALIGN_RIGHT, Font.CR_RED);
			
			if (ammotype1.Amount == ammotype1.MaxAmount) {
				DrawString (BigFont, "MAX", (-3,-50), DI_SCREEN_RIGHT_BOTTOM|DI_TEXT_ALIGN_RIGHT, Font.CR_RED);
			}
			
		}
		
		if (ammotype2 != null) 
		{
			DrawString (BigFont, FormatNumber(ammotype2.Amount, 3), (-3,-23), DI_SCREEN_RIGHT_BOTTOM|DI_TEXT_ALIGN_RIGHT, Font.CR_RED);
		}
		
		
		
		//The next thing drawn here is the mugshot. A lot more simple than the two above features.
		if (devrhud_displaymug) {
			DrawImage ("MUGDOME0", (devrhud_mugshotpos,0), DI_SCREEN_CENTER_BOTTOM|DI_ITEM_CENTER_BOTTOM);
			DrawTexture (GetMugShot(5), (devrhud_mugshotpos,-8), DI_SCREEN_CENTER_BOTTOM|DI_ITEM_CENTER_BOTTOM);
		
			if (crit_mug_fade_in) {
				crit_mug_alpha += deltaTic * 0.1;
			} else {
				crit_mug_alpha -= deltaTic * 0.1;
			}
			
			if (crit_mug_alpha >= 1) {
				crit_mug_fade_in = false;
			}
			else if (crit_mug_alpha <= 0) {
				crit_mug_fade_in = true;
			}
		
			if (CPlayer.health <= 25) {
				DrawImage ("MUGDOME1", (devrhud_mugshotpos,0), DI_SCREEN_CENTER_BOTTOM|DI_ITEM_CENTER_BOTTOM, crit_mug_alpha);
			}
		}
		//And finally, the key bar to display all keys. Making all the important parts of the HUD complete.
		DrawImage ("KEYBAR", (0,0), DI_SCREEN_LEFT_TOP|DI_ITEM_LEFT_TOP);
		
		if (CheckInventory("BlueCard", 1)) {
			DrawImage ("KB_BKEY", (3,3), DI_SCREEN_LEFT_TOP|DI_ITEM_LEFT_TOP);
		}
		
		if (CheckInventory("RedCard", 1)) {
			DrawImage ("KB_RKEY", (19,3), DI_SCREEN_LEFT_TOP|DI_ITEM_LEFT_TOP);
		}
		
		if (CheckInventory("YellowCard", 1)) {
			DrawImage ("KB_YKEY", (35,3), DI_SCREEN_LEFT_TOP|DI_ITEM_LEFT_TOP);
		}
		
		if (CheckInventory("BlueSkull", 1)) {
			DrawImage ("KB_BSKU", (55,2), DI_SCREEN_LEFT_TOP|DI_ITEM_LEFT_TOP);
		}
		
		if (CheckInventory("RedSkull", 1)) {
			DrawImage ("KB_RSKU", (71,2), DI_SCREEN_LEFT_TOP|DI_ITEM_LEFT_TOP);
		}
		
		if (CheckInventory("YellowSkull", 1)) {
			DrawImage ("KB_YSKU", (87,2), DI_SCREEN_LEFT_TOP|DI_ITEM_LEFT_TOP);
		}
		
	}
	
}